#! /bin/sh
#PBS -j oe
#PBS -l nodes=100:ppn=32:xe
#PBS -l walltime=24:00:00
#PBS -q normal
#PBS -N cd-hit

cd $PBS_O_WORKDIR

source /opt/modules/default/init/bash

aprun -n 100 -d31 -cc none \
 /mnt/a/u/sciteam/sadkhin/efi_precompute_bw_5/scheduler.x \
 /mnt/a/u/sciteam/sadkhin/efi_precompute_bw_5/lists/pfam/list.scheduler \
 /mnt/a/u/sciteam/sadkhin/efi_precompute_bw_5/1-generate_representative_sequences.pl  > log
