#! /bin/sh
#PBS -j oe
#PBS -l nodes=300:ppn=32:xe
#PBS -l walltime=24:00:00
#PBS -q normal
#PBS -N cdhit_testing

cd $PBS_O_WORKDIR

source /opt/modules/default/init/bash

aprun -n 300 -d31 -cc none \
 /mnt/a/u/sciteam/sadkhin/efi_precompute_bw_7/scheduler.x \
 /mnt/a/u/sciteam/sadkhin/efi_precompute_bw_7/lists/clan/list.scheduler \
 /u/sciteam/sadkhin/efi_precompute_bw_7/0-test_representatives.pl  > log
