#!/usr/bin/env perl
use strict;
use Getopt::Long;
my $family_type ;
my $list_of_completed_bins;
GetOptions ("bins=s" => \$list_of_completed_bins,    
		"family_type=s"  => \$family_type)   
or die("Error in command line arguments\n");
my $usage = "\tbins=<file containing list of bins> family=<pfam/ssf/gene3d/clans>";
print "Family type = $family_type\n";
print "List of completed_bins = $list_of_completed_bins\n";
die $usage unless( defined ($family_type) && defined($list_of_completed_bins) && -s ($list_of_completed_bins));


my $dir = $ENV{'EST_PRECOMPUTE_SCRIPTS'};
die "Input pfam/gene3d/ssf unless " unless defined $family_type;
die "Load EST Module\n" unless defined $dir;


print "about to move\n";
my $output_dir =("$dir/qsub/$family_type/blast/$list_of_completed_bins-dir");
mkdir($output_dir);

open F, $list_of_completed_bins or die $!;

while(<F>){
	chomp;
	my $qsub =  "$dir/qsub/$family_type/blast/$_.autogenerated.qsub";
	print STDERR "Checking if $qsub exists\n";
	if(-s $qsub)
	{
		my $command = "mv $dir/qsub/$family_type/blast/$_.autogenerated* $output_dir";
		print $command,"\n";  
		system($command);
	}
}
