#! /bin/sh
#PBS -j oe
#PBS -l nodes=300:ppn=32:xe
#PBS -l walltime=24:00:00
#PBS -q normal
#PBS -N gene3d_blast_reduce
source /opt/modules/default/init/bash
cd $PBS_O_WORKDIR

aprun -n 300 -N 1 -d 31   \
	      /mnt/a/u/sciteam/sadkhin/efi_precompute_bw_7/scheduler.x \
	      /mnt/a/u/sciteam/sadkhin/efi_precompute_bw_7/lists/gene3d/list.scheduler60gb \
	      /u/sciteam/sadkhin/efi_precompute_bw_7/5-blast_reduce.pl  > blast_reduce.log 
