#! /bin/sh
#PBS -j oe
#PBS -l nodes=100:ppn=32:xe
#PBS -l walltime=24:00:00
#PBS -q normal
#PBS -N repSequences_pfam
#PBS -m ae
#PBS -M youremail@illinois.edu

source /opt/modules/default/init/bash
module load /mnt/a/u/sciteam/sadkhin/modules/est-precompute/52
cd $PBS_O_WORKDIR
dir=$EST_PRECOMPUTE_SCRIPTS


aprun -n 100 -d31 -cc none \
 $dir/scheduler.x \
 $dir/lists/pfam/list.scheduler \
 $dir/1-generate_representative_sequences.pl  > logs/repSequences_pfam.log
