#! /bin/sh
#PBS -j oe
#PBS -l nodes=50:ppn=32:xe
#PBS -l walltime=24:00:00
#PBS -q normal
#PBS -N sort_blast_small_pfam
#PBS -m ae
#PBS -M youremail@illinois.edu

source /opt/modules/default/init/bash
module load ~/modules/est-precompute/49
cd $PBS_O_WORKDIR
dir=$EST_PRECOMPUTE
script="5-sort_blast_small.pl"
config="$dir/lists/pfam/list.scheduler"
log="logs/$script.log"
call="$SCHEDULER_X $config $dir/$script"
echo "running $script on $config ($call)"

aprun -n 400 -N 8 -d 4 $call > $log
