#! /bin/sh
#PBS -j oe
#PBS -l nodes=2:ppn=32:xe
#PBS -l walltime=24:00:00
#PBS -q normal
#PBS -N demultiplex_pfam
#PBS -m ae
#PBS -M youremail@illinois.edu

source /opt/modules/default/init/bash
module load /mnt/a/u/sciteam/sadkhin/modules/est-precompute/52
cd $PBS_O_WORKDIR
dir=$EST_PRECOMPUTE_SCRIPTS
script="5-demultiplex.pl"
config="$dir/lists/pfam/list.scheduler"
log="logs/$script.log"
call="$SCHEDULER_X $config $dir/$script"
echo "running $script on $config ($call)"

aprun -n 64 -N 32 -d 1 $call > $log
