#! /bin/sh
#PBS -j oe
#PBS -l nodes=10:ppn=32:xe
#PBS -l walltime=24:00:00
#PBS -q normal
#PBS -N cdhit_pfam
#PBS -m ae
#PBS -M youremail@illinois.edu

source /opt/modules/default/init/bash
module load /mnt/a/u/sciteam/sadkhin/modules/est-precompute/52
cd $PBS_O_WORKDIR
dir=$EST_PRECOMPUTE_SCRIPTS


aprun -n 10 -d31 -cc none \
 $dir/scheduler.x \
 $dir/lists/pfam/list.scheduler \
 $dir/7-cdhit.pl  > logs/7-cdhit.pl.log
