#! /bin/sh
#PBS -j oe
#PBS -l nodes=3:ppn=32:xe
#PBS -l walltime=24:00:00
#PBS -q normal
#PBS -N xgmml
#PBS -m ae
#PBS -M youremail@illinois.edu

source /opt/modules/default/init/bash
module load /mnt/a/u/sciteam/sadkhin/modules/est-precompute/52
cd $PBS_O_WORKDIR
dir=$EST_PRECOMPUTE_SCRIPTS
script="7-xgmml_new.pl"
config="$dir/lists/pfam/list.scheduler"
log="logs/$script.log"
call="$SCHEDULER_X $config $dir/$script"
echo "running $script on $config ($call)"

aprun -n 48  -N 16 -d 2 $call > $log
